# ---- Build stage ----
FROM golang:alpine AS builder
ARG GIT_COMMIT
ARG GO_BUILD_TAGS
WORKDIR /src
# Copy source
COPY ./src .

# Build static binary
RUN CGO_ENABLED=0 GOOS=linux go build -tags "${GO_BUILD_TAGS}" -trimpath -ldflags="-s -w -X main.gBuildPlatform=alpine" -o /tmp/open-blocklist

# ---- Runtime image ----

FROM alpine

RUN apk add --no-cache ca-certificates libcap

# Copy binary
COPY --from=builder /tmp/open-blocklist /usr/local/bin/open-blocklist

# Allow to bind to ports below 1024
RUN setcap 'cap_net_bind_service=+ep' /usr/local/bin/open-blocklist && mkdir /tls && chown 1000 /tls

USER 1000
EXPOSE 5353 8080 8090 8443 9100

ENTRYPOINT ["/usr/local/bin/open-blocklist"]
