# ---- Build stage ----

FROM cgr.dev/chainguard/go:latest AS builder
ARG GIT_COMMIT
ARG GO_BUILD_TAGS
WORKDIR /srv
COPY ./src .
RUN CGO_ENABLED=0 go build -tags "${GO_BUILD_TAGS}" -trimpath -ldflags="-s -w -X main.gBuildPlatform=wolfi" -o /tmp/open-blocklist

# ---- Runtime stage ----

FROM cgr.dev/chainguard/wolfi-base
RUN apk add --no-cache libcap libcap-utils
COPY --from=builder /tmp/open-blocklist /usr/local/bin/open-blocklist

RUN setcap cap_net_bind_service=+ep /usr/local/bin/open-blocklist && mkdir -p /tls && chown nonroot /tls
USER nonroot
EXPOSE 8080 8090 8443 9100
ENTRYPOINT ["/usr/local/bin/open-blocklist"]
