
networks:
  openbl_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:

  etcd:
    image: ${ETCD_IMAGE:-registry.k8s.io/etcd:3.5.15-0}
    container_name: open-blocklist-etcd
    hostname: etcd

    command: >
      /usr/local/bin/etcd
      --advertise-client-urls=http://0.0.0.0:2379
      --listen-client-urls=http://0.0.0.0:2379
      --data-dir=/etcd-data

    networks:
      openbl_net:
        ipv4_address: 172.30.0.20

    ports:
      - "${ETCD_HOST_PORT:-2379}:2379"

    volumes:
      - open-blocklist-etcd-data:/etcd-data


  open-blocklist:
    image: ${OPEN_BLOCKLIST_IMAGE:-ghcr.io/nashcom/open-blocklist:latest}
    container_name: open-blocklist-main
    hostname: open-blocklist

    depends_on:
      - etcd

    networks:
      openbl_net:
        ipv4_address: 172.30.0.10

    environment:
      - OPENBL_ETCD_ENDPOINT=http://172.30.0.20:2379
      - OPENBL_LOGLEVEL=DEBUG

    ports:
      - "${LOOKUP_HOST_PORT:-8080}:8080"
      - "${BLOCK_HOST_PORT:-8090}:8090"
      - "${METRICS_HOST_PORT:-9100}:9100"
      - "${DNS_HOST_PORT:-5353}:5353/udp"
      - "${DNS_HOST_PORT:-5353}:5353/tcp"


  coredns:
    image: ${COREDNS_IMAGE:-coredns/coredns:latest}
    container_name: open-blocklist-dns
    hostname: dns

    depends_on:
      - open-blocklist
      - etcd

    networks:
      openbl_net:
        ipv4_address: 172.30.0.30

    volumes:
      - ./Corefile:/Corefile:ro

    command: -conf /Corefile

    ports:
      - "${DNS_HOST_PORT:-55}:53/udp"
      - "${DNS_HOST_PORT:-55}:53/tcp"


volumes:
  open-blocklist-etcd-data:

